const countriesTypes = {
  GETTING_COUNTRIES: 'GETTING_COUNTRIES',
  SET_COUNTRIES: 'SET_COUNTRIES',
  SET_COUNTRIES_REGION_FILTER: 'SET_COUNTRIES_REGION_FILTER',
  SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
};

export default countriesTypes;
